/** International dial codes — generated from REST Countries API. Sorted by code (+1 first). */
export type CountryDialCode = {
  iso: string;
  dial: string;
  name: string;
};

export const COUNTRY_DIAL_CODES: CountryDialCode[] = [
  { iso: 'CA', dial: '+1', name: 'Canada' },
  { iso: 'DO', dial: '+1', name: 'Dominican Republic' },
  { iso: 'JM', dial: '+1', name: 'Jamaica' },
  { iso: 'PR', dial: '+1', name: 'Puerto Rico' },
  { iso: 'US', dial: '+1', name: 'United States' },
  { iso: 'SH', dial: '+2', name: 'Saint Helena, Ascension and Tristan da Cunha' },
  { iso: 'EH', dial: '+2', name: 'Western Sahara' },
  { iso: 'VA', dial: '+3', name: 'Vatican City' },
  { iso: 'KZ', dial: '+7', name: 'Kazakhstan' },
  { iso: 'RU', dial: '+7', name: 'Russia' },
  { iso: 'EG', dial: '+20', name: 'Egypt' },
  { iso: 'ZA', dial: '+27', name: 'South Africa' },
  { iso: 'GR', dial: '+30', name: 'Greece' },
  { iso: 'NL', dial: '+31', name: 'Netherlands' },
  { iso: 'BE', dial: '+32', name: 'Belgium' },
  { iso: 'FR', dial: '+33', name: 'France' },
  { iso: 'ES', dial: '+34', name: 'Spain' },
  { iso: 'HU', dial: '+36', name: 'Hungary' },
  { iso: 'IT', dial: '+39', name: 'Italy' },
  { iso: 'RO', dial: '+40', name: 'Romania' },
  { iso: 'CH', dial: '+41', name: 'Switzerland' },
  { iso: 'AT', dial: '+43', name: 'Austria' },
  { iso: 'GG', dial: '+44', name: 'Guernsey' },
  { iso: 'IM', dial: '+44', name: 'Isle of Man' },
  { iso: 'JE', dial: '+44', name: 'Jersey' },
  { iso: 'GB', dial: '+44', name: 'United Kingdom' },
  { iso: 'DK', dial: '+45', name: 'Denmark' },
  { iso: 'SE', dial: '+46', name: 'Sweden' },
  { iso: 'BV', dial: '+47', name: 'Bouvet Island' },
  { iso: 'NO', dial: '+47', name: 'Norway' },
  { iso: 'PL', dial: '+48', name: 'Poland' },
  { iso: 'DE', dial: '+49', name: 'Germany' },
  { iso: 'PE', dial: '+51', name: 'Peru' },
  { iso: 'MX', dial: '+52', name: 'Mexico' },
  { iso: 'CU', dial: '+53', name: 'Cuba' },
  { iso: 'AR', dial: '+54', name: 'Argentina' },
  { iso: 'BR', dial: '+55', name: 'Brazil' },
  { iso: 'CL', dial: '+56', name: 'Chile' },
  { iso: 'CO', dial: '+57', name: 'Colombia' },
  { iso: 'VE', dial: '+58', name: 'Venezuela' },
  { iso: 'MY', dial: '+60', name: 'Malaysia' },
  { iso: 'AU', dial: '+61', name: 'Australia' },
  { iso: 'CX', dial: '+61', name: 'Christmas Island' },
  { iso: 'CC', dial: '+61', name: 'Cocos (Keeling) Islands' },
  { iso: 'ID', dial: '+62', name: 'Indonesia' },
  { iso: 'PH', dial: '+63', name: 'Philippines' },
  { iso: 'NZ', dial: '+64', name: 'New Zealand' },
  { iso: 'PN', dial: '+64', name: 'Pitcairn Islands' },
  { iso: 'SG', dial: '+65', name: 'Singapore' },
  { iso: 'TH', dial: '+66', name: 'Thailand' },
  { iso: 'JP', dial: '+81', name: 'Japan' },
  { iso: 'KR', dial: '+82', name: 'South Korea' },
  { iso: 'VN', dial: '+84', name: 'Vietnam' },
  { iso: 'CN', dial: '+86', name: 'China' },
  { iso: 'TR', dial: '+90', name: 'Turkey' },
  { iso: 'IN', dial: '+91', name: 'India' },
  { iso: 'PK', dial: '+92', name: 'Pakistan' },
  { iso: 'AF', dial: '+93', name: 'Afghanistan' },
  { iso: 'LK', dial: '+94', name: 'Sri Lanka' },
  { iso: 'MM', dial: '+95', name: 'Myanmar' },
  { iso: 'IR', dial: '+98', name: 'Iran' },
  { iso: 'SS', dial: '+211', name: 'South Sudan' },
  { iso: 'MA', dial: '+212', name: 'Morocco' },
  { iso: 'DZ', dial: '+213', name: 'Algeria' },
  { iso: 'TN', dial: '+216', name: 'Tunisia' },
  { iso: 'LY', dial: '+218', name: 'Libya' },
  { iso: 'GM', dial: '+220', name: 'Gambia' },
  { iso: 'SN', dial: '+221', name: 'Senegal' },
  { iso: 'MR', dial: '+222', name: 'Mauritania' },
  { iso: 'ML', dial: '+223', name: 'Mali' },
  { iso: 'GN', dial: '+224', name: 'Guinea' },
  { iso: 'CI', dial: '+225', name: 'Ivory Coast' },
  { iso: 'BF', dial: '+226', name: 'Burkina Faso' },
  { iso: 'NE', dial: '+227', name: 'Niger' },
  { iso: 'TG', dial: '+228', name: 'Togo' },
  { iso: 'BJ', dial: '+229', name: 'Benin' },
  { iso: 'MU', dial: '+230', name: 'Mauritius' },
  { iso: 'LR', dial: '+231', name: 'Liberia' },
  { iso: 'SL', dial: '+232', name: 'Sierra Leone' },
  { iso: 'GH', dial: '+233', name: 'Ghana' },
  { iso: 'NG', dial: '+234', name: 'Nigeria' },
  { iso: 'TD', dial: '+235', name: 'Chad' },
  { iso: 'CF', dial: '+236', name: 'Central African Republic' },
  { iso: 'CM', dial: '+237', name: 'Cameroon' },
  { iso: 'CV', dial: '+238', name: 'Cape Verde' },
  { iso: 'ST', dial: '+239', name: 'São Tomé and Príncipe' },
  { iso: 'GQ', dial: '+240', name: 'Equatorial Guinea' },
  { iso: 'GA', dial: '+241', name: 'Gabon' },
  { iso: 'CG', dial: '+242', name: 'Republic of the Congo' },
  { iso: 'CD', dial: '+243', name: 'DR Congo' },
  { iso: 'AO', dial: '+244', name: 'Angola' },
  { iso: 'GW', dial: '+245', name: 'Guinea-Bissau' },
  { iso: 'IO', dial: '+246', name: 'British Indian Ocean Territory' },
  { iso: 'SC', dial: '+248', name: 'Seychelles' },
  { iso: 'SD', dial: '+249', name: 'Sudan' },
  { iso: 'RW', dial: '+250', name: 'Rwanda' },
  { iso: 'ET', dial: '+251', name: 'Ethiopia' },
  { iso: 'SO', dial: '+252', name: 'Somalia' },
  { iso: 'DJ', dial: '+253', name: 'Djibouti' },
  { iso: 'KE', dial: '+254', name: 'Kenya' },
  { iso: 'TZ', dial: '+255', name: 'Tanzania' },
  { iso: 'UG', dial: '+256', name: 'Uganda' },
  { iso: 'BI', dial: '+257', name: 'Burundi' },
  { iso: 'MZ', dial: '+258', name: 'Mozambique' },
  { iso: 'ZM', dial: '+260', name: 'Zambia' },
  { iso: 'MG', dial: '+261', name: 'Madagascar' },
  { iso: 'TF', dial: '+262', name: 'French Southern and Antarctic Lands' },
  { iso: 'YT', dial: '+262', name: 'Mayotte' },
  { iso: 'RE', dial: '+262', name: 'Réunion' },
  { iso: 'ZW', dial: '+263', name: 'Zimbabwe' },
  { iso: 'NA', dial: '+264', name: 'Namibia' },
  { iso: 'MW', dial: '+265', name: 'Malawi' },
  { iso: 'LS', dial: '+266', name: 'Lesotho' },
  { iso: 'BW', dial: '+267', name: 'Botswana' },
  { iso: 'SZ', dial: '+268', name: 'Eswatini' },
  { iso: 'UM', dial: '+268', name: 'United States Minor Outlying Islands' },
  { iso: 'KM', dial: '+269', name: 'Comoros' },
  { iso: 'ER', dial: '+291', name: 'Eritrea' },
  { iso: 'AW', dial: '+297', name: 'Aruba' },
  { iso: 'FO', dial: '+298', name: 'Faroe Islands' },
  { iso: 'GL', dial: '+299', name: 'Greenland' },
  { iso: 'GI', dial: '+350', name: 'Gibraltar' },
  { iso: 'PT', dial: '+351', name: 'Portugal' },
  { iso: 'LU', dial: '+352', name: 'Luxembourg' },
  { iso: 'IE', dial: '+353', name: 'Ireland' },
  { iso: 'IS', dial: '+354', name: 'Iceland' },
  { iso: 'AL', dial: '+355', name: 'Albania' },
  { iso: 'MT', dial: '+356', name: 'Malta' },
  { iso: 'CY', dial: '+357', name: 'Cyprus' },
  { iso: 'FI', dial: '+358', name: 'Finland' },
  { iso: 'BG', dial: '+359', name: 'Bulgaria' },
  { iso: 'LT', dial: '+370', name: 'Lithuania' },
  { iso: 'LV', dial: '+371', name: 'Latvia' },
  { iso: 'EE', dial: '+372', name: 'Estonia' },
  { iso: 'MD', dial: '+373', name: 'Moldova' },
  { iso: 'AM', dial: '+374', name: 'Armenia' },
  { iso: 'BY', dial: '+375', name: 'Belarus' },
  { iso: 'AD', dial: '+376', name: 'Andorra' },
  { iso: 'MC', dial: '+377', name: 'Monaco' },
  { iso: 'SM', dial: '+378', name: 'San Marino' },
  { iso: 'UA', dial: '+380', name: 'Ukraine' },
  { iso: 'RS', dial: '+381', name: 'Serbia' },
  { iso: 'ME', dial: '+382', name: 'Montenegro' },
  { iso: 'XK', dial: '+383', name: 'Kosovo' },
  { iso: 'HR', dial: '+385', name: 'Croatia' },
  { iso: 'SI', dial: '+386', name: 'Slovenia' },
  { iso: 'BA', dial: '+387', name: 'Bosnia and Herzegovina' },
  { iso: 'MK', dial: '+389', name: 'North Macedonia' },
  { iso: 'CZ', dial: '+420', name: 'Czechia' },
  { iso: 'SK', dial: '+421', name: 'Slovakia' },
  { iso: 'LI', dial: '+423', name: 'Liechtenstein' },
  { iso: 'FK', dial: '+500', name: 'Falkland Islands' },
  { iso: 'GS', dial: '+500', name: 'South Georgia' },
  { iso: 'BZ', dial: '+501', name: 'Belize' },
  { iso: 'GT', dial: '+502', name: 'Guatemala' },
  { iso: 'SV', dial: '+503', name: 'El Salvador' },
  { iso: 'HN', dial: '+504', name: 'Honduras' },
  { iso: 'NI', dial: '+505', name: 'Nicaragua' },
  { iso: 'CR', dial: '+506', name: 'Costa Rica' },
  { iso: 'PA', dial: '+507', name: 'Panama' },
  { iso: 'PM', dial: '+508', name: 'Saint Pierre and Miquelon' },
  { iso: 'HT', dial: '+509', name: 'Haiti' },
  { iso: 'GP', dial: '+590', name: 'Guadeloupe' },
  { iso: 'BL', dial: '+590', name: 'Saint Barthélemy' },
  { iso: 'MF', dial: '+590', name: 'Saint Martin' },
  { iso: 'BO', dial: '+591', name: 'Bolivia' },
  { iso: 'GY', dial: '+592', name: 'Guyana' },
  { iso: 'EC', dial: '+593', name: 'Ecuador' },
  { iso: 'GF', dial: '+594', name: 'French Guiana' },
  { iso: 'PY', dial: '+595', name: 'Paraguay' },
  { iso: 'MQ', dial: '+596', name: 'Martinique' },
  { iso: 'SR', dial: '+597', name: 'Suriname' },
  { iso: 'UY', dial: '+598', name: 'Uruguay' },
  { iso: 'BQ', dial: '+599', name: 'Caribbean Netherlands' },
  { iso: 'CW', dial: '+599', name: 'Curaçao' },
  { iso: 'TL', dial: '+670', name: 'Timor-Leste' },
  { iso: 'NF', dial: '+672', name: 'Norfolk Island' },
  { iso: 'BN', dial: '+673', name: 'Brunei' },
  { iso: 'NR', dial: '+674', name: 'Nauru' },
  { iso: 'PG', dial: '+675', name: 'Papua New Guinea' },
  { iso: 'TO', dial: '+676', name: 'Tonga' },
  { iso: 'SB', dial: '+677', name: 'Solomon Islands' },
  { iso: 'VU', dial: '+678', name: 'Vanuatu' },
  { iso: 'FJ', dial: '+679', name: 'Fiji' },
  { iso: 'PW', dial: '+680', name: 'Palau' },
  { iso: 'WF', dial: '+681', name: 'Wallis and Futuna' },
  { iso: 'CK', dial: '+682', name: 'Cook Islands' },
  { iso: 'NU', dial: '+683', name: 'Niue' },
  { iso: 'WS', dial: '+685', name: 'Samoa' },
  { iso: 'KI', dial: '+686', name: 'Kiribati' },
  { iso: 'NC', dial: '+687', name: 'New Caledonia' },
  { iso: 'TV', dial: '+688', name: 'Tuvalu' },
  { iso: 'PF', dial: '+689', name: 'French Polynesia' },
  { iso: 'TK', dial: '+690', name: 'Tokelau' },
  { iso: 'FM', dial: '+691', name: 'Micronesia' },
  { iso: 'MH', dial: '+692', name: 'Marshall Islands' },
  { iso: 'KP', dial: '+850', name: 'North Korea' },
  { iso: 'HK', dial: '+852', name: 'Hong Kong' },
  { iso: 'MO', dial: '+853', name: 'Macau' },
  { iso: 'KH', dial: '+855', name: 'Cambodia' },
  { iso: 'LA', dial: '+856', name: 'Laos' },
  { iso: 'BD', dial: '+880', name: 'Bangladesh' },
  { iso: 'TW', dial: '+886', name: 'Taiwan' },
  { iso: 'MV', dial: '+960', name: 'Maldives' },
  { iso: 'LB', dial: '+961', name: 'Lebanon' },
  { iso: 'JO', dial: '+962', name: 'Jordan' },
  { iso: 'SY', dial: '+963', name: 'Syria' },
  { iso: 'IQ', dial: '+964', name: 'Iraq' },
  { iso: 'KW', dial: '+965', name: 'Kuwait' },
  { iso: 'SA', dial: '+966', name: 'Saudi Arabia' },
  { iso: 'YE', dial: '+967', name: 'Yemen' },
  { iso: 'OM', dial: '+968', name: 'Oman' },
  { iso: 'PS', dial: '+970', name: 'Palestine' },
  { iso: 'AE', dial: '+971', name: 'United Arab Emirates' },
  { iso: 'IL', dial: '+972', name: 'Israel' },
  { iso: 'BH', dial: '+973', name: 'Bahrain' },
  { iso: 'QA', dial: '+974', name: 'Qatar' },
  { iso: 'BT', dial: '+975', name: 'Bhutan' },
  { iso: 'MN', dial: '+976', name: 'Mongolia' },
  { iso: 'NP', dial: '+977', name: 'Nepal' },
  { iso: 'TJ', dial: '+992', name: 'Tajikistan' },
  { iso: 'TM', dial: '+993', name: 'Turkmenistan' },
  { iso: 'AZ', dial: '+994', name: 'Azerbaijan' },
  { iso: 'GE', dial: '+995', name: 'Georgia' },
  { iso: 'KG', dial: '+996', name: 'Kyrgyzstan' },
  { iso: 'UZ', dial: '+998', name: 'Uzbekistan' },
  { iso: 'BS', dial: '+1242', name: 'Bahamas' },
  { iso: 'BB', dial: '+1246', name: 'Barbados' },
  { iso: 'AI', dial: '+1264', name: 'Anguilla' },
  { iso: 'AG', dial: '+1268', name: 'Antigua and Barbuda' },
  { iso: 'VG', dial: '+1284', name: 'British Virgin Islands' },
  { iso: 'VI', dial: '+1340', name: 'United States Virgin Islands' },
  { iso: 'KY', dial: '+1345', name: 'Cayman Islands' },
  { iso: 'BM', dial: '+1441', name: 'Bermuda' },
  { iso: 'GD', dial: '+1473', name: 'Grenada' },
  { iso: 'TC', dial: '+1649', name: 'Turks and Caicos Islands' },
  { iso: 'MS', dial: '+1664', name: 'Montserrat' },
  { iso: 'MP', dial: '+1670', name: 'Northern Mariana Islands' },
  { iso: 'GU', dial: '+1671', name: 'Guam' },
  { iso: 'AS', dial: '+1684', name: 'American Samoa' },
  { iso: 'SX', dial: '+1721', name: 'Sint Maarten' },
  { iso: 'LC', dial: '+1758', name: 'Saint Lucia' },
  { iso: 'DM', dial: '+1767', name: 'Dominica' },
  { iso: 'VC', dial: '+1784', name: 'Saint Vincent and the Grenadines' },
  { iso: 'TT', dial: '+1868', name: 'Trinidad and Tobago' },
  { iso: 'KN', dial: '+1869', name: 'Saint Kitts and Nevis' },
  { iso: 'SJ', dial: '+4779', name: 'Svalbard and Jan Mayen' },
  { iso: 'AX', dial: '+35818', name: 'Åland Islands' },
];

export function getDialCodeByIso(iso: string): string | undefined {
  return COUNTRY_DIAL_CODES.find((entry) => entry.iso === iso)?.dial;
}
